name: fishing-harbor-bot-test

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - ../.env.dist

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    env_file:
      - ../.env.dist
    volumes:
      - ..:/app
    depends_on:
      - db

volumes:
  postgres_data_test: